import { describe, expect, it } from 'vitest';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
import { mkdtemp, readFile, stat, rm, writeFile, symlink } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { loadConfig } from '../src/config.js';
import { LemonSqueezyClient } from '../src/api/client.js';
import { buildServer } from '../src/server.js';

type Call={url:URL;init:RequestInit};
async function fixture(options:{env?:NodeJS.ProcessEnv;noKey?:boolean;responder?:(call:Call,index:number)=>Response|Promise<Response>}={}){
 const calls:Call[]=[];const config=loadConfig({LEMONSQUEEZY_MIN_REQUEST_INTERVAL_MS:'0',...(options.noKey?{}:{LEMONSQUEEZY_API_KEY:'fixture-api-a',LEMONSQUEEZY_LICENSE_KEY:'fixture-license-a'}),...options.env});
 const fetcher=(async(url:any,init:RequestInit)=>{const call={url:new URL(String(url)),init};calls.push(call);if(options.responder)return options.responder(call,calls.length-1);if(call.url.pathname==='/v1/users/me')return Response.json({meta:{test_mode:true},data:{type:'users',id:'fixture',attributes:{}}});return Response.json({data:{type:'customers',id:'created',attributes:{}}});}) as typeof fetch;
 const api=new LemonSqueezyClient(config,fetcher),server=buildServer(config,api),client=new Client({name:'lemon-native-fixture',version:'1'});const[a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);
 const call=async(name:string,args:Record<string,any>={})=>{const result=await client.callTool({name,arguments:args});return{result,value:JSON.parse((result.content as any[])[0].text)};};return{calls,api,client,call,close:async()=>{await client.close();await server.close();}};
}
const identity=()=>Response.json({meta:{test_mode:true},data:{type:'users',id:'fixture'}});
describe('reviewed native API and isolated credentials',()=>{
 it('discovers65 tools/44 reads/21 confirmed effects credential-free',async()=>{const f=await fixture({noKey:true});try{const{tools}=await f.client.listTools();expect(tools).toHaveLength(65);expect(tools.filter(t=>t.annotations?.readOnlyHint)).toHaveLength(44);expect(tools.filter(t=>(t.inputSchema.properties as any).confirm)).toHaveLength(21);expect((await f.call('list_accounts')).value).toEqual({accounts:[]});expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('uses actual JSON:API headers, native page filters/includes and one profile-mode preflight',async()=>{const f=await fixture();try{expect((await f.call('list_orders',{page:2,per_page:25,store_id:'123',include:'customer'})).result.isError).toBeFalsy();const c=f.calls[1]!;expect(c.url.origin).toBe('https://api.lemonsqueezy.com');expect(c.url.searchParams.get('page[number]')).toBe('2');expect(c.url.searchParams.get('page[size]')).toBe('25');expect(c.url.searchParams.get('filter[store_id]')).toBe('123');expect(c.url.searchParams.get('include')).toBe('customer');expect(c.init.headers).toMatchObject({Accept:'application/vnd.api+json','Content-Type':'application/vnd.api+json',Authorization:'Bearer fixture-api-a'});expect(c.init.redirect).toBe('error');await f.call('list_products');expect(f.calls.filter(c=>c.url.pathname==='/v1/users/me')).toHaveLength(1);}finally{await f.close();}});
 it('refuses a mismatched live key before the requested operation',async()=>{const f=await fixture({responder:()=>Response.json({meta:{test_mode:false},data:{type:'users'}})});try{expect((await f.call('list_orders')).result.isError).toBe(true);expect(f.calls.map(c=>c.url.pathname)).toEqual(['/v1/users/me']);}finally{await f.close();}});
 it('requires explicit live mode and still checks the actual upstream key',async()=>{const f=await fixture({env:{LEMONSQUEEZY_MODE:'live'},responder:c=>c.url.pathname==='/v1/users/me'?Response.json({meta:{test_mode:false},data:{type:'users'}}):Response.json({data:[]})});try{expect((await f.call('list_orders')).result.isError).toBeFalsy();expect(f.calls).toHaveLength(2);}finally{await f.close();}});
 it('named profiles never inherit either global credential',()=>{const c=loadConfig({LEMONSQUEEZY_API_KEY:'global',LEMONSQUEEZY_LICENSE_KEY:'global-license',LEMONSQUEEZY_ACCOUNTS:'[{"name":"isolated"}]'});expect(c.accounts[0]).toMatchObject({apiToken:'',licenseKey:'',mode:'test'});});
 it.each([{LEMONSQUEEZY_ACCOUNTS:'[{"name":"a"},{"name":"a"}]'},{LEMONSQUEEZY_API_KEY:'fixture',LEMONSQUEEZY_TOKEN_FILE:'/tmp/file'},{LEMONSQUEEZY_LICENSE_KEY:'fixture',LEMONSQUEEZY_LICENSE_FILE:'/tmp/file'},{LEMONSQUEEZY_MODE:'production'},{LEMONSQUEEZY_ACCOUNTS:'[{"name":"a","host":"https://other.example"}]'}])('rejects ambiguous or unsupported profile settings %j',env=>expect(()=>loadConfig(env)).toThrow());
 it('uses the independent License API credential/form fields without a main key or Authorization header',async()=>{const f=await fixture({noKey:true,env:{LEMONSQUEEZY_LICENSE_KEY:'private-license-fixture'},responder:()=>Response.json({valid:true,error:null,license_key:{key:'private-license-fixture'},meta:{store_id:1}})});try{const r=await f.call('validate_license',{instance_id:'known-instance'});expect(r.result.isError).toBeFalsy();expect(f.calls).toHaveLength(1);const c=f.calls[0]!;expect(c.init.headers).toMatchObject({Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'});expect((c.init.headers as any).Authorization).toBeUndefined();expect(new URLSearchParams(String(c.init.body)).get('license_key')).toBe('private-license-fixture');expect(new URLSearchParams(String(c.init.body)).get('instance_id')).toBe('known-instance');expect(JSON.stringify(r.value)).not.toContain('private-license-fixture');}finally{await f.close();}});
 it('allows a native valid:false license verdict as data',async()=>{const f=await fixture({responder:()=>Response.json({valid:false,error:'Expired',license_key:null})});try{const r=await f.call('validate_license');expect(r.result.isError).toBeFalsy();expect(r.value.valid).toBe(false);}finally{await f.close();}});
 it('treats native activated:false as failure even in a successful HTTP response',async()=>{const f=await fixture({responder:()=>Response.json({activated:false,error:'Limit reached',license_key:{key:'fixture-license-a'}})});try{const r=await f.call('activate_license',{instance_name:'Fixture',confirm:true});expect(r.result.isError).toBe(true);expect(f.calls).toHaveLength(1);expect(JSON.stringify(r.value)).not.toContain('fixture-license-a');}finally{await f.close();}});
 it('rejects a raw license credential in tool arguments',async()=>{const f=await fixture();try{expect((await f.call('validate_license',{license_key:'unsafe-cli-key'})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it.each([{per_page:101},{store_id:'../bad'},{include:'unknown'},{unknown:'field'}])('refuses invalid list arguments %j before network',async args=>{const f=await fixture();try{expect((await f.call('list_orders',args)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('builds native JSON:API attributes/relationships from flat CLI fields',async()=>{const f=await fixture();try{expect((await f.call('create_customer',{store_id:'123',name:'Fixture',email:'fixture@example.com',confirm:true})).result.isError).toBeFalsy();expect(JSON.parse(String(f.calls[1]!.init.body))).toEqual({data:{type:'customers',attributes:{name:'Fixture',email:'fixture@example.com'},relationships:{store:{data:{type:'stores',id:'123'}}}}});}finally{await f.close();}});
 it('preserves billing flags and nullable native pause in a subscription PATCH',async()=>{const f=await fixture();try{expect((await f.call('update_subscription',{id:'42',pause:null,invoice_immediately:true,disable_prorations:false,confirm:true})).result.isError).toBeFalsy();expect(JSON.parse(String(f.calls[1]!.init.body))).toEqual({data:{type:'subscriptions',id:'42',attributes:{pause:null,invoice_immediately:true,disable_prorations:false}}});}finally{await f.close();}});
 it.each([{id:'42'},{id:'42',payload:{data:{type:'subscriptions',id:'other',attributes:{cancelled:true}}}},{id:'42',payload:{data:{type:'subscriptions',id:'42',attributes:{cancelled:true}}},cancelled:false}])('refuses empty, mismatched or mixed PATCH bodies %j',async args=>{const f=await fixture();try{expect((await f.call('update_subscription',{...args,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it.each([{id:'42',confirm:true},{id:'42',amount:100,full_refund:true,confirm:true},{id:'42',amount:0,confirm:true}])('refuses accidental or ambiguous refunds %j',async args=>{const f=await fixture();try{expect((await f.call('refund_order',args)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it.each([{amount:100},{full_refund:true}])('sends only explicitly requested partial/full refund intent %j',async intent=>{const f=await fixture();try{expect((await f.call('refund_order',{id:'42',...intent,confirm:true})).result.isError).toBeFalsy();const body=JSON.parse(String(f.calls[1]!.init.body));expect(body).toEqual({data:{type:'orders',id:'42',attributes:'amount' in intent?{amount:100}:{}}});}finally{await f.close();}});
 it('reads usage records using GET despite the misleading primary heading',async()=>{const f=await fixture();try{await f.call('get_usage_record',{id:'42'});expect(f.calls[1]!.init.method).toBe('GET');}finally{await f.close();}});
 it('does not retry429 or an unknown transport outcome after the mode preflight',async()=>{for(const responder of [(c:Call)=>c.url.pathname==='/v1/users/me'?identity():Response.json({errors:[{detail:'rate limited'}]},{status:429}),(c:Call)=>{if(c.url.pathname==='/v1/users/me')return identity();throw Error('transport failed');}]){const f=await fixture({responder});try{expect((await f.call('cancel_subscription',{id:'42',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(2);}finally{await f.close();}}});
 it('redacts API keys, license credentials and signed URLs in error receipts',async()=>{const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({errors:[{detail:'fixture-api-a fixture-license-a https://store.example/path?signature=private'}]},{status:403})});try{const r=await f.call('list_orders');expect(r.result.isError).toBe(true);expect(JSON.stringify(r.value)).not.toMatch(/fixture-api-a|fixture-license-a|signature=private/);}finally{await f.close();}});
});
describe('private result contracts',()=>{
 it('retains native license status while removing only actual credential fields',async()=>{const f=await fixture({responder:()=>Response.json({valid:true,license_key:{key:'fixture-license-a',status:'active',activation_limit:3},meta:{product_id:2}})});try{const r=await f.call('validate_license');expect(r.result.isError).toBeFalsy();expect(r.value.license_key).toEqual({key:'[redacted]',status:'active',activation_limit:3});}finally{await f.close();}});
 it('redacts native checkout custom-path credentials from ordinary reads',async()=>{const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({data:{type:'checkouts',attributes:{url:'https://store.lemonsqueezy.com/checkout/custom/private-fixture'}}})});try{const r=await f.call('get_checkout',{id:'42'});expect(r.result.isError).toBeFalsy();expect(JSON.stringify(r.value)).not.toContain('private-fixture');expect(JSON.stringify(r.value)).toContain('[private checkout URL]');}finally{await f.close();}});
 it('does not accept an empty successful license effect as a native receipt',async()=>{const f=await fixture({responder:()=>new Response(null,{status:204})});try{expect((await f.call('activate_license',{instance_name:'Fixture',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(1);}finally{await f.close();}});
});
describe('shared effect guard and reviewed workflow',()=>{
 it('refuses all effects without approval, including private exports and POST license activation',async()=>{const f=await fixture();try{for(const[name,args]of [['refund_order',{id:'42',amount:1}],['activate_license',{instance_name:'Fixture'}],['export_resources',{operation:'list_orders',output_file:'/tmp/not-created-lemon.json'}]] as const)expect((await f.call(name,args)).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('read-only hides21 effects and refuses direct hidden confirmed calls',async()=>{const f=await fixture({env:{LEMONSQUEEZY_READ_ONLY:'1'}});try{expect((await f.client.listTools()).tools).toHaveLength(44);expect((await f.call('refund_order',{id:'42',amount:1,confirm:true})).result.isError).toBe(true);expect((await f.call('activate_license',{instance_name:'Fixture',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('ALLOW_DESTRUCTIVE=0 refuses a confirmed financial action',async()=>{const f=await fixture({env:{LEMONSQUEEZY_ALLOW_DESTRUCTIVE:'0'}});try{expect((await f.call('refund_order',{id:'42',amount:1,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('batch validation refuses any invalid later task before provider or credential reads',async()=>{const f=await fixture();try{const tasks=[{tool:'cancel_subscription',arguments:{id:'42'}},{tool:'refund_order',arguments:{id:'42'}}];expect((await f.call('preview_commerce_batch',{tasks})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('binds exact amounts and request order to the local review hash',async()=>{const f=await fixture();try{const tasks=[{tool:'refund_order',arguments:{id:'42',amount:100}},{tool:'cancel_subscription',arguments:{id:'42'}}];const preview=await f.call('preview_commerce_batch',{tasks});expect(preview.result.isError).toBeFalsy();expect(f.calls).toHaveLength(0);for(const changed of [[tasks[1],tasks[0]],[{...tasks[0],arguments:{id:'42',amount:101}},tasks[1]]]){expect((await f.call('submit_commerce_batch',{tasks:changed,review_sha256:preview.value.reviewSha256,confirm:true})).result.isError).toBe(true);}expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('batch stops at an unknown failure with known outcomes and unattempted indices',async()=>{const f=await fixture({responder:(c,i)=>c.url.pathname==='/v1/users/me'?identity():i===2?Response.json({errors:[{detail:'fixture failure'}]},{status:500}):Response.json({data:{type:'subscriptions',id:'42'}})});try{const tasks=Array.from({length:3},(_,i)=>({tool:'cancel_subscription',arguments:{id:String(i+1)}}));const p=await f.call('preview_commerce_batch',{tasks});const r=await f.call('submit_commerce_batch',{tasks,review_sha256:p.value.reviewSha256,confirm:true});expect(r.result.isError).toBe(true);const receipt=JSON.parse(r.value.error);expect(receipt.failedIndex).toBe(1);expect(receipt.knownResults).toHaveLength(1);expect(receipt.unattemptedIndices).toEqual([2]);expect(f.calls).toHaveLength(3);}finally{await f.close();}});
});
describe('private native outputs and bounded exports',()=>{
 it('generates invoice with native POST query fields and sends no JSON body',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-invoice-'));const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({meta:{urls:{download_invoice:'https://store.example/invoice?signature=private-fixture'}}})});try{const output_file=join(dir,'invoice.json');const r=await f.call('generate_order_invoice',{id:'42',name:'Fixture',address:'1 Fixture Road',city:'Fixture',zip_code:'12345',country:'GB',output_file,confirm:true});expect(r.result.isError).toBeFalsy();const c=f.calls[1]!;expect(c.init.method).toBe('POST');expect(c.init.body).toBeUndefined();expect(c.url.searchParams.get('name')).toBe('Fixture');expect(c.url.searchParams.get('zip_code')).toBe('12345');expect(JSON.stringify(r.value)).not.toContain('signature');expect(await readFile(output_file,'utf8')).toContain('signature=private-fixture');if(process.platform!=='win32')expect((await stat(output_file)).mode&0o777).toBe(0o600);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('refuses invoice US/CA country without state before network',async()=>{const f=await fixture();try{expect((await f.call('generate_order_invoice',{id:'42',name:'Fixture',address:'a',city:'c',zip_code:'1',country:'US',output_file:'/tmp/not-created.json',confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}});
 it('never overwrites existing signed-output files or sends the provider effect',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-existing-'));const f=await fixture();try{const output_file=join(dir,'existing.json');await writeFile(output_file,'original');expect((await f.call('create_checkout',{store_id:'1',variant_id:'2',output_file,confirm:true})).result.isError).toBe(true);expect(f.calls).toHaveLength(0);expect(await readFile(output_file,'utf8')).toBe('original');}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('exports native pages with included resources and exact cap continuation',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-export-'));const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({data:[{type:'orders',id:'1'},{type:'orders',id:'2'},{type:'orders',id:'3'}],included:[{type:'customers',id:'1',attributes:{urls:{portal:'https://store.example/?signature=private'}}}],meta:{page:{currentPage:1,lastPage:2}},links:{next:'https://untrusted.example/do-not-follow'}})});try{const output_file=join(dir,'bounded.json');const r=await f.call('export_resources',{operation:'list_orders',arguments:{per_page:3,store_id:'1'},max_items:2,output_file,confirm:true});expect(r.result.isError).toBeFalsy();expect(r.value.completeWithinRequestedFilters).toBe(false);expect(r.value.continuation).toEqual({operation:'list_orders',arguments:{per_page:3,store_id:'1',page:1},start_offset:2});const exported=JSON.parse(await readFile(output_file,'utf8'));expect(exported.data).toHaveLength(2);expect(exported.included).toHaveLength(1);expect(JSON.stringify(exported)).not.toContain('signature=private');expect(f.calls).toHaveLength(2);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('uses native lastPage, not guessed short-page completeness',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-pages-'));const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({data:[{type:'orders',id:c.url.searchParams.get('page[number]')}],meta:{page:{currentPage:Number(c.url.searchParams.get('page[number]')),lastPage:2}}})});try{const r=await f.call('export_resources',{operation:'list_orders',output_file:join(dir,'pages.json'),confirm:true});expect(r.result.isError).toBeFalsy();expect(r.value.requests).toBe(2);expect(r.value.items).toBe(2);expect(r.value.completeWithinRequestedFilters).toBe(true);expect(r.value.atomicSnapshot).toBe(false);expect(f.calls.slice(1).map(c=>c.url.searchParams.get('page[number]'))).toEqual(['1','2']);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('resumes inside a native page with the explicit receipt offset',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-resume-'));const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({data:[{type:'orders',id:'1'},{type:'orders',id:'2'}],meta:{page:{currentPage:4,lastPage:4}}})});try{const output_file=join(dir,'resumed.json');const r=await f.call('export_resources',{operation:'list_orders',arguments:{page:4,per_page:2},start_offset:1,output_file,confirm:true});expect(r.result.isError).toBeFalsy();expect(JSON.parse(await readFile(output_file,'utf8')).data).toEqual([{type:'orders',id:'2'}]);expect(r.value.completeWithinRequestedFilters).toBe(true);}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('rejects malformed pagination and leaves no completed output file',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-invalid-page-'));const f=await fixture({responder:c=>c.url.pathname==='/v1/users/me'?identity():Response.json({data:[],meta:{page:{currentPage:9,lastPage:10}}})});try{const output_file=join(dir,'invalid.json');expect((await f.call('export_resources',{operation:'list_orders',output_file,confirm:true})).result.isError).toBe(true);await expect(stat(output_file)).rejects.toThrow();}finally{await f.close();await rm(dir,{recursive:true,force:true});}});
 it('requires owner-only regular credential files and refuses symlink credentials',async()=>{const dir=await mkdtemp(join(tmpdir(),'lemon-key-'));try{const token_file=join(dir,'key'),link=join(dir,'link');await writeFile(token_file,'private-file-fixture',{mode:0o600});await symlink(token_file,link);const f=await fixture({noKey:true,env:{LEMONSQUEEZY_TOKEN_FILE:link}});try{expect((await f.call('get_user')).result.isError).toBe(true);expect(f.calls).toHaveLength(0);}finally{await f.close();}}finally{await rm(dir,{recursive:true,force:true});}});
});
