import{open,lstat}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';
import{selectAccount,type Account,type Config}from'../config.js';import{LemonSqueezyError,UsageError}from'./errors.js';import operations from'../tools/operations.json'with{type:'json'};
export type Json=Record<string,any>;export type QueryParam={name:string;value:unknown;explode?:boolean};const MAX=5*1048576;
const routes=operations.map(o=>({method:o.method,regex:new RegExp('^'+o.path.replace(/[.*+?^$()|[\]\\]/g,'\\$&').replace(/\{[^}]+\}/g,'([^/]+)')+'$')}));
export class LemonSqueezyClient{
 private tokens=new Map<string,string>();private modes=new Map<string,boolean>();private schedule:Promise<void>=Promise.resolve();private nextAt=0;
 constructor(readonly config:Config,private readonly fetcher:typeof fetch=fetch,private readonly sleep:(ms:number)=>Promise<void>=ms=>new Promise(r=>setTimeout(r,ms))){}
 redactText(text:string){for(const secret of [...this.config.accounts.flatMap(a=>[a.apiToken,a.licenseKey]),...this.tokens.values()].filter(Boolean).sort((a,b)=>b.length-a.length))text=text.split(secret).join('[redacted]');return text.replace(/https?:\/\/[^\s"<>]*\/checkout\/custom\/[^\s"<>]*/gi,'[private checkout URL]').replace(/https?:\/\/[^\s"<>]*(?:X-Amz-Signature|[?&](?:token|signature|sig|key|access_token)=)[^\s"<>]*/gi,'[private credential URL]');}
 sanitize(v:unknown):unknown{if(typeof v==='string')return this.redactText(v);if(Array.isArray(v))return v.map(x=>this.sanitize(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,/^(password|secret|api_key|key|license_key|licenseKey|signing_key|api_token|token|access_token|refresh_token|authorization|client_secret)$/i.test(k)&&!(k==='license_key'&&x&&typeof x==='object')?'[redacted]':this.sanitize(x)]));return v;}
 private async credential(a:Account,license=false){const label=a.name+':'+(license?'license':'api');if(this.tokens.has(label))return this.tokens.get(label)!;let token=license?a.licenseKey:a.apiToken;const path=license?a.licenseFile:a.tokenFile;if(path){let file;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();file=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await file.stat();if(!stat.isFile()||stat.size>65536||(process.platform!=='win32'&&((stat.mode&0o077)||stat.uid!==process.getuid?.())))throw Error();token=(await file.readFile('utf8')).trim();}catch{throw new LemonSqueezyError('Cannot read the selected private credential file; use an absolute owner-only regular token-only file at most 64 KiB.',0,'CONFIG');}finally{await file?.close();}}if(!token||/[\r\n]/.test(token))throw new LemonSqueezyError('No valid '+(license?'license credential':'API key')+' configured for the selected profile. Run lemonsqueezy-cli login.',0,'CONFIG');this.tokens.set(label,token);return token;}
 private async pace(){const next=this.schedule.catch(()=>{}).then(async()=>{const delay=Math.max(0,this.nextAt-Date.now());if(delay)await this.sleep(delay);this.nextAt=Date.now()+this.config.minIntervalMs;});this.schedule=next;await next;}
 private async bytes(response:Response){const chunks:Uint8Array[]=[];let total=0;const reader=response.body?.getReader();if(reader)try{for(;;){const part=await reader.read();if(part.done)break;total+=part.value.byteLength;if(total>MAX){await reader.cancel();throw new LemonSqueezyError('Response exceeds the 5 MiB local cap; no automatic retry.');}chunks.push(part.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
 private async send(a:Account,method:string,path:string,query:QueryParam[],body:unknown,license:boolean){
  const url=new URL('/v1'+path,'https://api.lemonsqueezy.com');for(const p of query){if(p.value===undefined||p.value===null)continue;if(typeof p.value==='object')throw new UsageError('Object or array query parameters are unsupported.');url.searchParams.set(p.name,String(p.value));}
  const secret=await this.credential(a,license);const headers:Record<string,string>={Accept:license?'application/json':'application/vnd.api+json','Content-Type':license?'application/x-www-form-urlencoded':'application/vnd.api+json','User-Agent':'Navid Media Lemon Squeezy MCP CLI/2.0.0 (https://navid.me)'};if(!license)headers.Authorization='Bearer '+secret;
  const encoded=license?new URLSearchParams({...body as Record<string,string>,license_key:secret}).toString():body===undefined?undefined:JSON.stringify(body);if(encoded!==undefined&&Buffer.byteLength(encoded)>1048576)throw new UsageError('Request exceeds the 1 MiB local cap.');
  await this.pace();let response:Response;try{response=await this.fetcher(url,{method,redirect:'error',signal:AbortSignal.timeout(this.config.timeoutMs),headers,...(encoded===undefined?{}:{body:encoded})});}catch{throw new LemonSqueezyError('Request failed or timed out. Outcome may be unknown; no automatic retry. Inspect provider state before deliberately repeating.',0,'NETWORK');}
  const bytes=await this.bytes(response);if(!response.ok){let detail='';try{detail=JSON.stringify(this.sanitize(JSON.parse(bytes.toString('utf8')))).slice(0,1000);}catch{}throw new LemonSqueezyError('Lemon Squeezy API '+response.status+(detail?': '+detail:''),response.status,response.status===429?'RATE_LIMIT':[401,403].includes(response.status)?'AUTH':'API_ERROR');}
  if(!bytes.length){if(!license&&method==='DELETE'&&response.status===204)return{http_status:response.status,success:true};throw new LemonSqueezyError('Missing native receipt; effect outcome may be unknown. No automatic retry.');}let parsed;try{parsed=JSON.parse(bytes.toString('utf8'));}catch{throw new LemonSqueezyError('Provider returned a non-JSON response; no automatic retry.');}if(!parsed||typeof parsed!=='object')throw new LemonSqueezyError('Invalid provider JSON response.');
  if(license){const resultField=path.endsWith('/activate')?'activated':path.endsWith('/deactivate')?'deactivated':'valid';if(typeof parsed[resultField]!=='boolean')throw new LemonSqueezyError('Invalid native license receipt.');if(resultField!=='valid'&&parsed[resultField]!==true)throw new LemonSqueezyError('Native license operation was not successful: '+this.redactText(String(parsed.error??'unknown failure')));}
  return parsed;
 }
 async request(method:string,path:string,query:QueryParam[]=[],body?:unknown,hint?:string):Promise<any>{
  if(!routes.some(r=>r.method===method&&r.regex.test(path))||/[?#\\]/.test(path)||/%2f|%5c|%00/i.test(path)||path.split('/').some(s=>['.','..'].includes(decodeURIComponent(s))))throw new UsageError('Unsupported Lemon Squeezy API method or path.');
  const a=selectAccount(this.config,hint),license=path.startsWith('/licenses/');
  if(!license&&path!=='/users/me'&&!this.modes.has(a.name)){const identity=await this.send(a,'GET','/users/me',[],undefined,false);if(typeof identity.meta?.test_mode!=='boolean'||identity.meta.test_mode!==(a.mode==='test'))throw new LemonSqueezyError('API-key test/live mode does not match the selected private profile. No requested operation was sent.',0,'CONFIG');this.modes.set(a.name,identity.meta.test_mode);}
  const value=await this.send(a,method,path,query,body,license);if(!license&&path==='/users/me'){if(typeof value.meta?.test_mode!=='boolean'||value.meta.test_mode!==(a.mode==='test'))throw new LemonSqueezyError('API-key test/live mode does not match the selected private profile.',0,'CONFIG');this.modes.set(a.name,value.meta.test_mode);}return value;
 }
}
