export type Account={name:string;apiToken:string;tokenFile:string;licenseKey:string;licenseFile:string;mode:'test'|'live'};
export type Config={accounts:Account[];defaultAccount:string;readOnly:boolean;allowDestructive:boolean;auditPath:string;timeoutMs:number;minIntervalMs:number};
function integer(v:string|undefined,fallback:number,min:number,max:number){const n=v?Number(v):fallback;if(!Number.isInteger(n)||n<min||n>max)throw Error('Invalid request timeout or pacing settings.');return n;}
export function loadConfig(env:NodeJS.ProcessEnv=process.env):Config{
 if(env.LEMONSQUEEZY_MODE&&!['test','live'].includes(env.LEMONSQUEEZY_MODE))throw Error('LEMONSQUEEZY_MODE must be test or live.');
 let entries:Record<string,unknown>[]=[];
 if(env.LEMONSQUEEZY_ACCOUNTS){try{const v=JSON.parse(env.LEMONSQUEEZY_ACCOUNTS);if(!Array.isArray(v))throw Error();entries=v;}catch{throw Error('LEMONSQUEEZY_ACCOUNTS must be a private JSON array of named profiles.');}}
 else if(env.LEMONSQUEEZY_API_KEY||env.LEMONSQUEEZY_TOKEN_FILE||env.LEMONSQUEEZY_LICENSE_KEY||env.LEMONSQUEEZY_LICENSE_FILE)entries=[{name:'default',api_key:env.LEMONSQUEEZY_API_KEY,token_file:env.LEMONSQUEEZY_TOKEN_FILE,license_key:env.LEMONSQUEEZY_LICENSE_KEY,license_file:env.LEMONSQUEEZY_LICENSE_FILE,mode:env.LEMONSQUEEZY_MODE??'test'}];
 const accounts=entries.map(x=>{if(!x||typeof x!=='object'||typeof x.name!=='string'||!x.name.trim())throw Error('Every Lemon Squeezy profile requires a nonempty name.');for(const k of ['api_key','token_file','license_key','license_file'])if(x[k]!==undefined&&(typeof x[k]!=='string'||/[\r\n]/.test(x[k]as string)))throw Error('Private profile settings must be strings without line breaks.');if(x.api_key&&x.token_file||x.license_key&&x.license_file)throw Error('Select one private source per credential type.');if(Object.keys(x).some(k=>!['name','api_key','token_file','license_key','license_file','mode'].includes(k)))throw Error('Unsupported private profile setting.');const mode=x.mode??'test';if(mode!=='test'&&mode!=='live')throw Error('Profile mode must be test or live.');return{name:x.name.trim(),apiToken:String(x.api_key??''),tokenFile:String(x.token_file??''),licenseKey:String(x.license_key??''),licenseFile:String(x.license_file??''),mode} as Account;});
 if(new Set(accounts.map(a=>a.name)).size!==accounts.length)throw Error('Profile names must be unique.');
 const defaultAccount=env.LEMONSQUEEZY_DEFAULT_ACCOUNT??accounts[0]?.name??'';if(defaultAccount&&!accounts.some(a=>a.name===defaultAccount))throw Error('Unknown LEMONSQUEEZY_DEFAULT_ACCOUNT.');
 return{accounts,defaultAccount,readOnly:/^(1|true)$/i.test(env.LEMONSQUEEZY_READ_ONLY??''),allowDestructive:!/^(0|false)$/i.test(env.LEMONSQUEEZY_ALLOW_DESTRUCTIVE??''),auditPath:env.LEMONSQUEEZY_AUDIT_LOG??'',timeoutMs:integer(env.LEMONSQUEEZY_REQUEST_TIMEOUT_MS,30000,100,300000),minIntervalMs:integer(env.LEMONSQUEEZY_MIN_REQUEST_INTERVAL_MS,1000,0,10000)};
}
export function selectAccount(c:Config,hint?:string):Account{const a=c.accounts.find(a=>a.name===(hint??c.defaultAccount));if(!a)throw Error(c.accounts.length?'Unknown profile; run list_accounts and use its exact label.':'No credentials configured. Set LEMONSQUEEZY_API_KEY or LEMONSQUEEZY_LICENSE_FILE privately; run lemonsqueezy-cli login.');return a;}
