import operationsData from'./operations.json'with{type:'json'};import provenance from'./provenance.json'with{type:'json'};import{Ajv,type ValidateFunction}from'ajv';import addFormats from'ajv-formats';import{open,lstat,unlink}from'node:fs/promises';import{constants}from'node:fs';import{isAbsolute}from'node:path';import{createHash}from'node:crypto';
import{LemonSqueezyClient,type Json,type QueryParam}from'../api/client.js';import{LemonSqueezyError,UsageError}from'../api/errors.js';import{selectAccount,type Config}from'../config.js';import type{Risk}from'../safety.js';
export type Operation={name:string;operationId:string;title:string;description:string;method:string;path:string;group:string;risk:Risk;params:{name:string;key:string;in:string;required:boolean;schema:Json;style:string;explode:boolean}[];bodySchema:Json|null;bodyRequired:boolean;privateOutput:boolean;attributes:Json;relationships:Json;includes:string[];licenseAPI:boolean};
export type ToolSpec={name:string;title:string;description:string;group:string;inputSchema:Json;risk:Risk;handler:(args:Json,client:LemonSqueezyClient)=>Promise<unknown>};
const operations=operationsData as unknown as Operation[];const ajv=new Ajv({allErrors:true,strict:false,formats:{int64:true}});(addFormats as unknown as(a:Ajv)=>void)(ajv);
const bodyValidators=new Map(operations.filter(o=>o.bodySchema).map(o=>[o.name,ajv.compile(o.bodySchema!)]));
function check(v:ValidateFunction,a:unknown){if(!v(a))throw new UsageError(ajv.errorsText(v.errors,{separator:'; '}));}
function fieldsFor(op:Operation){const properties:Json=Object.fromEntries(op.params.map(p=>[p.key,p.schema]));Object.assign(properties,op.attributes);for(const [name,s]of Object.entries(op.relationships)){const many=(s as Json).properties.data.type==='array';properties[name.replace(/-/g,'_')+(many?'_ids':'_id')]=many?{type:'array',minItems:1,maxItems:100,items:{type:'string',pattern:'^[A-Za-z0-9_-]+$'}}:{type:'string',pattern:'^[A-Za-z0-9_-]+$'};}if(op.name.startsWith('refund_'))properties.full_refund={type:'boolean',description:'Explicit full-refund intent. Must be true with no amount; cannot coexist with amount.'};properties.account={type:'string',description:'Exact private profile label. Does not prove store ownership; mode applies to the main API key only.'};if(op.risk!=='read')properties.confirm={type:'boolean',description:'Explicit approval for this requested effect, including private output files.'};if(op.bodySchema){properties.payload={...op.bodySchema,description:'Complete native JSON object body. JSON:API uses data/type/id/attributes/relationships. No mixing with body flags or payload_file. License credential is private configuration, never body input.'};properties.payload_file={type:'string',minLength:1,description:'Absolute regular non-symlink native JSON body file at most 1 MiB; cannot mix with payload or body flags.'};}if(op.privateOutput)properties.output_file={type:'string',minLength:1,description:'Required absolute NEW private file for the signed checkout/invoice URL; exclusive0600, no overwrite.'};return{type:'object',properties,required:[...op.params.filter(p=>p.required).map(p=>p.key),...(op.privateOutput?['output_file']:[])],additionalProperties:false};}
async function fileJSON(path:string){let f;try{if(!isAbsolute(path)||(await lstat(path)).isSymbolicLink())throw Error();f=await open(path,constants.O_RDONLY|(constants.O_NOFOLLOW??0));const stat=await f.stat();if(!stat.isFile()||stat.size>1048576)throw Error();return JSON.parse(await f.readFile('utf8'));}catch{throw new UsageError('payload_file must be an absolute regular non-symlink JSON body file, at most 1 MiB.');}finally{await f?.close();}}
function semantics(op:Operation,args:Json,body:any){
 if(args.id&&(!/^[A-Za-z0-9_-]+$/.test(args.id)))throw new UsageError('id must be an exact non-traversing resource ID.');
 if(args.include&&args.include.split(',').some((name:string)=>!op.includes.includes(name)))throw new UsageError('Unsupported include relationship for this native resource.');
 if(op.licenseAPI)return;
 const data=body?.data,attrs=data?.attributes;
 if(data&&args.id&&data.id!==args.id)throw new UsageError('Native body resource id must match the exact path id.');
 if(op.name.startsWith('update_')&&(!attrs||!Object.keys(attrs).length))throw new UsageError('Update requires at least one native attribute.');
 if(op.name.startsWith('refund_')){if(args.full_refund===true&&attrs?.amount!==undefined)throw new UsageError('Choose amount or explicit full_refund, not both.');if(attrs?.amount===undefined&&args.full_refund!==true)throw new UsageError('Refund requires amount or explicit full_refund: true. Omission alone must never mean full refund.');}
 if(op.name==='create_discount'){if(attrs.amount_type==='percent'&&attrs.amount>100)throw new UsageError('Percent discount cannot exceed100.');if(attrs.is_limited_redemptions===true&&!attrs.max_redemptions)throw new UsageError('Limited redemptions require max_redemptions.');if(attrs.is_limited_to_products===true&&!data.relationships?.variants?.data?.length)throw new UsageError('Limited products require explicit variants.');}
 if(op.name.startsWith('generate_')&&['US','CA'].includes(args.country)&&!args.state)throw new UsageError('Invoice country US/CA requires state.');
 for(const value of [attrs?.url,...(attrs?.product_options?.media??[]),attrs?.product_options?.redirect_url,attrs?.product_options?.receipt_link_url].filter(Boolean)){let u;try{u=new URL(value);}catch{throw new UsageError('Invalid provider callback or media URL.');}if(u.protocol!=='https:'||u.username||u.password)throw new UsageError('Provider callback/media URLs must use HTTPS without embedded credentials.');}
}
async function prepare(op:Operation,args:Json){
 const flat=Object.fromEntries(Object.keys(op.attributes).filter(k=>args[k]!==undefined).map(k=>[k,args[k]]));const relationships:Json={};for(const [name,s]of Object.entries(op.relationships)){const linkage=(s as Json).properties.data,many=linkage.type==='array',key=name.replace(/-/g,'_')+(many?'_ids':'_id');if(args[key]!==undefined)relationships[name]={data:many?args[key].map((id:string)=>({type:linkage.items.properties.type.const,id})):{type:linkage.properties.type.const,id:args[key]}};}
 if((args.payload!==undefined||args.payload_file!==undefined)&&(Object.keys(flat).length||Object.keys(relationships).length))throw new UsageError('Do not mix native body flags with payload/payload_file.');if(args.payload!==undefined&&args.payload_file!==undefined)throw new UsageError('Use payload or payload_file, not both.');
 const formed=op.licenseAPI?flat:{data:{type:op.group,...(args.id?{id:args.id}:{}),attributes:flat,...(Object.keys(op.relationships).length?{relationships}:{})}};
 const body=op.bodySchema?(args.payload_file?await fileJSON(args.payload_file):args.payload??formed):undefined;if(op.bodySchema)check(bodyValidators.get(op.name)!,body);semantics(op,args,body);
 const path=op.params.filter(p=>p.in==='path').reduce((s,p)=>s.replace('{'+p.name+'}',encodeURIComponent(String(args[p.key]))),op.path);const query:QueryParam[]=op.params.filter(p=>p.in==='query'&&args[p.key]!==undefined).map(p=>({name:p.name,value:args[p.key],explode:p.explode}));return{method:op.method,path,query,body};
}
async function savePrivate(path:string,value:unknown){if(!isAbsolute(path))throw new UsageError('output_file must be absolute.');let f;try{f=await open(path,'wx',0o600);}catch{throw new UsageError('Cannot exclusively create output_file; never overwrites or follows a target symlink.');}try{const actual=typeof value==='function'?await (value as ()=>Promise<unknown>)():value;const bytes=Buffer.from(JSON.stringify(actual)+'\n');if(bytes.length>5*1048576)throw new UsageError('Private output exceeds the5MiB local cap.');await f.writeFile(bytes);return{saved:true,output_file:path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};}catch(e){await f.close();f=undefined;await unlink(path).catch(()=>{});throw e;}finally{await f?.close();}}
async function execute(op:Operation,args:Json,client:LemonSqueezyClient){const call=await prepare(op,args);const run=()=>client.request(call.method,call.path,call.query,call.body,args.account);return op.privateOutput?savePrivate(args.output_file,run):client.sanitize(await run());}
export const ALL_TOOLS:ToolSpec[]=operations.map(op=>({...op,inputSchema:fieldsFor(op),handler:(args,client)=>execute(op,args,client)}));
const account={type:'string',description:'Exact selected private account profile; binds label, not key ownership.'};const confirm={type:'boolean',description:'Explicit approval for this exact requested ordered batch.'};
function helper(name:string,title:string,description:string,risk:Risk,properties:Json,required:string[],handler:ToolSpec['handler']){ALL_TOOLS.push({name,title,description,group:'local_workflows',risk,inputSchema:{type:'object',properties,required,additionalProperties:false},handler});}
helper('list_accounts','List configured accounts','Local profile labels/default/auth method only. No keys, token paths, provider identity or network request.','read',{},[],async(_,c)=>({accounts:c.config.accounts.map(a=>({name:a.name,default:a.name===c.config.defaultAccount,mode:a.mode,mainAPIConfigured:!!(a.apiToken||a.tokenFile),licenseConfigured:!!(a.licenseKey||a.licenseFile),licenseModeVerified:false}))}));
helper('get_operation_schema','Inspect a current native operation','Local reviewed method/path/query/body schema and provenance for one native tool. No credentials or provider request.','read',{operation:{type:'string',enum:operations.map(o=>o.name),description:'Exact native tool name, e.g. update_subscription or refund_order.'}},['operation'],async a=>({operation:operations.find(o=>o.name===a.operation),source:provenance.source,checked:provenance.checked,snapshotSha256:provenance.sanitizedSnapshotSha256}));
const allowed=operations.filter(o=>o.risk!=='read'&&!o.privateOutput).map(o=>o.name);
const tasks={type:'array',minItems:1,maxItems:20,description:'One to twenty exact ordered commerce effects. No signed-output operations or mutable payload files. Financial effects require explicit native amount/full-refund intent; subscription changes can charge or alter recurring billing.',items:{type:'object',properties:{tool:{type:'string',enum:allowed},arguments:{type:'object',description:'Native arguments without account, confirm, payload_file or output_file.'}},required:['tool','arguments'],additionalProperties:false}};
function canonical(v:any):any{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));return v;}
function hash(v:any){return createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');}
async function reviewed(args:Json,c:LemonSqueezyClient){const selected=selectAccount(c.config,args.account);const calls=[];for(const task of args.tasks){if(!allowed.includes(task.tool))throw new UsageError('Unsupported commerce batch tool.');if(['account','confirm','payload_file','output_file'].some(k=>task.arguments[k]!==undefined))throw new UsageError('Batch arguments cannot override account/confirmation or reference mutable payload files.');const t=ALL_TOOLS.find(t=>t.name===task.tool)!,op=operations.find(o=>o.name===task.tool)!;validateArguments(t,task.arguments);calls.push(await prepare(op,task.arguments));}return{version:1,profile:selected.name,mode:selected.mode,credentialBinding:'profile label only; private credentials not hashed',snapshotSha256:provenance.sanitizedSnapshotSha256,tasks:args.tasks,calls};}
helper('preview_commerce_batch','Review exact ordered commerce tasks','Local validation and SHA-256 of exact inputs, request order, selected profile label/mode and reviewed native schema. No provider requests, secret load, store ownership check or financial guarantee.','read',{tasks,account},['tasks'],async(a,c)=>{const r=await reviewed(a,c);return{...c.sanitize(r)as Json,reviewSha256:hash(r),localOnly:true,providerValidated:false,notice:'Binds exact requests/order/profile label/mode/schema, not credentials or provider state. Credential rotation and upstream changes require renewed human review. License mode cannot be established by profile label. No expiry, single-use guarantee, rollback or payment outcome proof.'};});
helper('submit_commerce_batch','Execute reviewed commerce tasks','Confirmed one-to-twenty ordered effects. Prevalidate all and check the exact review hash before the first request. Stop on first failure with known results and unattempted indices; no retry, transaction, rollback or implicit continuation.','destructive',{tasks,account,confirm,review_sha256:{type:'string',pattern:'^[a-f0-9]{64}$',description:'Exact preview_commerce_batch hash for identical tasks, selected profile/mode/schema/order.'}},['tasks','review_sha256'],async(a,c)=>{const r=await reviewed(a,c);if(hash(r)!==a.review_sha256)throw new UsageError('Review hash mismatch; preview these exact tasks and profile again.');const knownResults:Json[]=[];for(let i=0;i<r.calls.length;i++){const call=r.calls[i]!;try{const result=c.sanitize(await c.request(call.method,call.path,call.query,call.body,r.profile));knownResults.push({index:i,tool:a.tasks[i].tool,result});}catch(e){const err=e as LemonSqueezyError;throw new LemonSqueezyError(JSON.stringify(c.sanitize({notice:'Batch stopped. Failed request may have an unknown outcome; inspect native state before repeating. No retries or rollback.',knownResults,failedIndex:i,unattemptedIndices:r.calls.slice(i+1).map((_,j)=>i+1+j),error:err.message})),err.status??0,err.code??'API_ERROR');}}return{requestsProcessed:true,knownResults,notice:'Native receipts are not independent settlement, access-revocation or notification-delivery proofs.'};});
const listOps=operations.filter(o=>o.name.startsWith('list_'));
helper('export_resources','Export bounded private native resources','Confirmed paginated JSON:API export to a new exclusive0600 file. Preserves data and included resources while redacting credentials/signed URLs. Uses native page counters, never follows links, downloads files or promises an atomic backup.','destructive',{operation:{type:'string',enum:listOps.map(o=>o.name)},arguments:{type:'object',description:'Actual selected list-operation filters/page/per_page/include only; no profile override.'},account,confirm,start_offset:{type:'integer',minimum:0,maximum:99},max_pages:{type:'integer',minimum:1,maximum:100,description:'Local budget default10.'},max_items:{type:'integer',minimum:1,maximum:10000,description:'Local budget default1000.'},output_file:{type:'string',minLength:1}},['operation','output_file'],async(a,c)=>{
 const op=listOps.find(o=>o.name===a.operation)!;const args=a.arguments??{};if(['account','confirm','payload_file','output_file'].some(k=>args[k]!==undefined))throw new UsageError('Export arguments cannot override private profile or output settings.');validateArguments(ALL_TOOLS.find(t=>t.name===op.name)!,args);
 let receipt:Json={};const saved=await savePrivate(a.output_file,async()=>{
 const per_page=args.per_page??100,maxPages=a.max_pages??10,maxItems=a.max_items??1000;let page=args.page??1,offset=a.start_offset??0,requests=0,complete=false;const data:Json[]=[],included:Json[]=[],seen=new Set<string>();if(offset>=per_page)throw new UsageError('start_offset must be lower than per_page.');
 while(requests<maxPages&&data.length<maxItems){const call=await prepare(op,{...args,page,per_page});const result=await c.request(call.method,call.path,call.query,call.body,a.account);requests++;const meta=result.meta?.page;if(!Array.isArray(result.data)||!meta||meta.currentPage!==page||!Number.isInteger(meta.lastPage)||meta.lastPage<page||result.data.length>per_page)throw new LemonSqueezyError('Invalid native JSON:API pagination receipt.');if(offset>result.data.length)throw new UsageError('Resume page changed; requested start_offset no longer exists.');const take=Math.min(result.data.length-offset,maxItems-data.length);data.push(...result.data.slice(offset,offset+take));if(result.included!==undefined&&!Array.isArray(result.included))throw new LemonSqueezyError('Invalid native included resources.');for(const row of result.included??[]){const key=row.type+':'+row.id;if(!seen.has(key)){included.push(row);seen.add(key);}}
 offset+=take;if(offset<result.data.length)break;if(page>=meta.lastPage){complete=true;break;}if(!result.data.length)throw new LemonSqueezyError('Empty native page before lastPage; export completeness cannot be established.');page++;offset=0;if(Buffer.byteLength(JSON.stringify({data,included}))>5*1048576)throw new LemonSqueezyError('Export exceeds the5MiB local cap.');}
 receipt={requests,items:data.length,completeWithinRequestedFilters:complete,continuation:complete?null:{operation:op.name,arguments:{...args,page,per_page},start_offset:offset},atomicSnapshot:false,credentialsAndSignedURLsRedacted:true};return{data:c.sanitize(data),included:c.sanitize(included),receipt};});return{...saved,...receipt};
});
const validators=new Map(ALL_TOOLS.map(t=>[t.name,ajv.compile(t.inputSchema)]));export function validateArguments(tool:ToolSpec,args:Json){check(validators.get(tool.name)!,args);}export function visibleTools(c:Config){return ALL_TOOLS.filter(t=>!c.readOnly||t.risk==='read');}
